version: '1'
services:
  #mysql:
  #  image: mysql:latest
  #  command: '--default-authentication-plugin=mysql_native_password'
  #  restart: always
  #  healthcheck:
  #    test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="" --silent']
  #    interval: 3s
  #    retries: 5
  #    start_period: 30s
  #  secrets:
  #    - db-password
  #  volumes:
  #    - db-data:/var/lib/mysql
  #  networks:
  #    - backnet
  #  environment:
  #    - MYSQL_DATABASE=shout
  #    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  #  expose:
  #    - 3306
  #    - 33060

  shoutai:
    build:
      context: shoutai
      target: builder
    restart: always
    environment:
      - DB_PWD=exmapleENVVAr
    ports:
      - 8000:8000
    networks:
      #- backnet
      - frontnet
    #depends_on:
    #  mysql:
    #    condition: service_healthy

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - shoutai
    networks:
      - frontnet

volumes:
  db-data:

#secrets:
#  db-password:
#    file: db/pwd.txt

networks:
  #backnet:
  frontnet: